import React from 'react';
import { Room, Nurse } from '../types/hospital';
import { BedDouble, ShieldCheck, Users } from 'lucide-react';

interface Unit1EViewProps { rooms: Room[]; nurses: Nurse[]; }

export const Unit1EView: React.FC<Unit1EViewProps> = ({ rooms, nurses }) => {
  return (
    <div className="space-y-4">
      <div className="bg-command-card border border-command-border rounded-lg p-4 flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div><div className="flex items-center gap-2 text-red-400 text-xs font-semibold uppercase"><span>The Heart Hospital Baylor Denton</span><span>•</span><span>Universal Cardiac Unit</span></div><h2 className="text-xl font-bold text-command-text">1 EAST UNIT MANAGEMENT (22 Beds)</h2></div>
        <div className="bg-command-dark px-3 py-2 rounded border border-purple-500/40 text-xs"><div className="text-purple-400 font-bold flex items-center gap-1"><ShieldCheck size={14} /> Protected STEMI Reserve: 1 Bed (1E-120)</div><div className="text-[10px] text-command-muted">Release Review: 05:30</div></div>
      </div>
      <div className="bg-command-card border border-command-border rounded-lg p-4"><h3 className="text-sm font-bold tracking-wide text-command-text mb-3 flex items-center gap-2"><Users size={16} className="text-command-accent" /> Nursing Assignments & Workload Capacity</h3><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">{nurses.map(nurse => <div key={nurse.id} className="bg-command-dark p-3 rounded border border-command-border text-xs space-y-2"><div className="flex items-center justify-between font-bold"><span className="text-command-text">{nurse.name}</span><span className={`px-2 py-0.5 rounded text-[10px] ${nurse.acuityLoad === 'Max' ? 'bg-red-500/20 text-red-400 border border-red-500/40' : 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/40'}`}>Acuity: {nurse.acuityLoad}</span></div><div className="text-command-muted">Assigned Rooms: <strong className="font-mono text-command-accent">{nurse.assignedRooms.join(', ')}</strong></div><div className="flex items-center justify-between text-[11px] pt-2 border-t border-command-border/60"><span>Workload Score: <strong className="text-command-text">{nurse.workloadScore}/10</strong></span><span>Remaining Cap: <strong className="text-emerald-400">{nurse.remainingCapacity} beds</strong></span></div>{nurse.isCharge && <div className="text-[10px] bg-amber-500/10 text-amber-400 px-2 py-0.5 rounded border border-amber-500/30">⚠️ Charge RN carrying patient assignment (reduces flexibility)</div>}</div>)}</div></div>
      <div className="bg-command-card border border-command-border rounded-lg p-4"><h3 className="text-sm font-bold tracking-wide text-command-text mb-3 flex items-center gap-2"><BedDouble size={16} className="text-command-accent" /> Detailed Room Status & Receiving Availability</h3><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">{rooms.map(room => <div key={room.id} className="bg-command-dark p-3 rounded border border-command-border text-xs space-y-1.5"><div className="flex items-center justify-between font-bold"><span className="text-sm text-command-accent">Room {room.number}</span><span className="px-2 py-0.5 rounded text-[10px] bg-command-border text-command-text">{room.levelOfCare}</span></div><div className="flex items-center justify-between"><span className="text-command-muted">State:</span><span className="font-semibold text-command-text">{room.state}</span></div><div className="flex items-center justify-between"><span className="text-command-muted">Receiving Ready:</span><span className={`font-semibold ${room.receivingAvailable ? 'text-emerald-400' : 'text-red-400'}`}>{room.receivingAvailable ? 'Yes' : 'No'}</span></div>{room.statusNote && <div className="text-[11px] text-command-muted italic pt-1 border-t border-command-border/40">Note: {room.statusNote}</div>}</div>)}</div></div>
    </div>
  );
};
